name: webhook

on:
  push:
    branches: [gh-pages]

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: wait 10 min
        run: sleep 600 # 等待 10 分钟

      - name: Send Webhook
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }} # 在 GitHub 仓库的 Secrets 中设置 WEBHOOK_URL
        run: |
          curl -X POST -H "X_PULL_TOKEN: ${{ secrets.X_PULL_TOKEN }}" -d '{"ref": "refs/heads/gh-pages"}' $WEBHOOK_URL